### PR TITLE
Update OTA submodule pointer.

### PR DESCRIPTION
**Pull request by ActoryOu**
We have patches for #3109, #3449, and #3461. Update OTA submodule pointer to fix those issues.

Description
-----------

We have patches for #3109, #3449, and #3461. Update OTA submodule pointer to fix those issues.
3109: ota [PR#428](https://github.com/aws/ota-for-aws-iot-embedded-sdk/pull/428).
3449: ota [PR#427](https://github.com/aws/ota-for-aws-iot-embedded-sdk/pull/427).
3461: ota [PR#426](https://github.com/aws/ota-for-aws-iot-embedded-sdk/pull/426).

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by pvyawaha — DISMISSED** [review]

**Comment by paulbartell** [comment]
Looks like this breaks a bunch of builds.

**Review by paulbartell — DISMISSED** [review]

**Review by ravibhagavandas — APPROVED** [review]

**Review by paulbartell — APPROVED** [review]

**Pull request merged**
