### PR TITLE
espressif iot_wifi.c: Fix log print for SYSTEM_EVENT_AP_STOP event

### PR DESCRIPTION
**Pull request by shubhamkulkarni97**
Description
-----------
Fixes issue reported in https://github.com/aws/amazon-freertos/issues/2925

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by alfred2g — APPROVED** [review]

**Review by cobusve — APPROVED** [review]

**Comment by shubhamkulkarni97** [comment]
Can we merge this PR?

**Pull request merged**
