### PR TITLE
Update kernel submodule pointer

### PR DESCRIPTION
**Pull request by ravibhagavandas**
Update FreeRTOS kernel submodule to point to latest commit

Description
-----------
This updates FreeRTOS kernel submodule from commit# 210b1ffcc87bcff93871a37fbf0ad2033870ecaf to commit#82fdc1c3ee4c5e8a1f10e2a2370c81088506e905

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ravibhagavandas** [comment]
PR is currently blocked on build failures for Marvell and ST which are being investigated.

**Comment by markrtuttle** [comment]
Feel free to contact me if you need help cleaning up these proof failures.

**Comment by AniruddhaKanhere** [comment]
Created an empty file `winbase.h` in `tools/cbmc/windows2` folder for CBMC to work. This addition was done due to the change in [this commit](https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/82fdc1c3ee4c5e8a1f10e2a2370c81088506e905).

**Review by AniruddhaKanhere — APPROVED** [review]
Approving the changes related to CBMC proofs/setup etc.

**Review by mingyue86010 — APPROVED** [review]

**Review by aggarg — APPROVED** [review]

**Pull request merged**
