### PR TITLE
updating cypress asset to submodules

### PR DESCRIPTION
**Pull request by shuopeng-deng**
Description
-----------

Update vendors/cypress asset to use submodules and update them to the lastest version.
Update projects/cypress accordingly to match new cypress asset
Checklist:
----------

- [ X] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by shuopeng-deng** [comment]
Replaces https://github.com/aws/amazon-freertos/pull/2759

**Comment by yourslab** [comment]
It seems there is a missing include for `core_json.h`:
```
../../../../../demos/device_shadow_for_aws/shadow_demo_main.c:75:10: fatal error: core_json.h: No such file or directory
 #include "core_json.h"
```

**Comment by shuopeng-deng** [comment]
make build for aws_demos is working correctly for me. The include path for core_json.h is added from:
/projects/cypress/make_support/mtb_afr_source.mk: line 342

**Comment by shuopeng-deng** [comment]
Nevermind, I see what I did wrong:
Should be:
$(CY_AFR_ROOT)/libraries/coreJSON/source/include
instead of
$(CY_AFR_ROOT)/libraries/coreJson/source/include

I only ran tests on a windows PC that ignored file name capitalization.

**Comment by yngki** [comment]
@shuopeng-deng can you please update the PR?  Thanks!

**Review by mingyue86010 — APPROVED** [review]

**Review by cobusve — APPROVED** [review]

**Comment by mingyue86010** [comment]
@shuopeng-deng I noticeed there are a lot of binary files added by this PR. Can you double check if those are all nessary?

**Comment by mingyue86010** [comment]
Looks like change the BLE code into static libs.

> @shuopeng-deng I noticeed there are a lot of binary files (.a and .ar files) added by this PR. Can you double check if those are all nessary?

Looks like change the BLE code into static libs.

**Pull request merged**
