### PR TITLE
Qiutongs/nuvoton eth fix

### PR DESCRIPTION
**Pull request by qiutongs**
Description
-----------

Related PR: https://github.com/aws/amazon-freertos/pull/1989

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by markrtuttle** [comment]
Feel free to contact me @markrtuttle if you want help fixing that CheckOptionsOuter proof, or contact @AniruddhaKanhere.

**Comment by htibosch** [comment]
> 
@aggarw13 wrote in PR #1989  :

> It seems that `prvSkipPastRemainingOptions` was removed in #2015 by @htibosch

I did not remove that function, but I **renamed** it to give it a more appropriate name: `prvReadSackOption()`,

I submitted a PR  #2029 to make the compilation of `prvReadSackOption()` dependant on `ipconfigUSE_TCP_WIN`.

PS. the CBMC checks for my PR #2029 are repaired, but there are build errors in the Nuvoton project(s). Can you see why it does not compile?

**Comment by qiutongs** [comment]
> > 
> 
> @aggarw13 wrote in PR #1989 :
> 
> > It seems that `prvSkipPastRemainingOptions` was removed in #2015 by @htibosch
> 
> I did not remove that function, but I **renamed** it to give it a more appropriate name: `prvReadSackOption()`,
> 
> I submitted a PR #2029 to make the compilation of `prvReadSackOption()` dependant on `ipconfigUSE_TCP_WIN`.
> 
> PS. the CBMC checks for my PR #2029 are repaired, but there are build errors in the Nuvoton project(s). Can you see why it does not compile?

The build errors were due to license problem on our test infra. We are in the process of buying new license for Nuvoton. Once that is done, I will re-run the build checks.

**Comment by qiutongs** [comment]
> > 
> 
> @aggarw13 wrote in PR #1989 :
> 
> > It seems that `prvSkipPastRemainingOptions` was removed in #2015 by @htibosch
> 
> I did not remove that function, but I **renamed** it to give it a more appropriate name: `prvReadSackOption()`,
> 
> I submitted a PR #2029 to make the compilation of `prvReadSackOption()` dependant on `ipconfigUSE_TCP_WIN`.
> 
> PS. the CBMC checks for my PR #2029 are repaired, but there are build errors in the Nuvoton project(s). Can you see why it does not compile?

We merged PR #2029. So I remove my duplicate code change and rebase this PR on top of it.

**Comment by qiutongs** [comment]
Waiting for new license of Keil to build Nuvoton project.

**Pull request merged**
