### PR TITLE
lwIP 2.1.2 redux

### PR DESCRIPTION
**Pull request by dan4thewin**
This PR replaces lwIP 2.0.3 with lwIP 2.1.2, along with fixes for breakage in the related Cypress code.  I've also added code to wake a task blocked on an mbox fetch if that mbox is freed.

### CODE REVIEW

**Comment by cobusve** [comment]
Looks good

**Comment by jainamt** [comment]
Dan, can you please update Changelog file as well. 

Also, for the changes done on top of the new LWIP, do we plan to send those patches upstream ?

**Pull request merged**
