### PR TITLE
Retrieve the JITR/JITP certificate from PKCS11

### PR DESCRIPTION
**Pull request by bryan-hunt**
Update TLS implementation to retrieve the JITR/JITP certificate from PKCS11

Description
-----------
iot_tls.c uses keyJITR_DEVICE_CERTIFICATE_AUTHORITY_PEM as a constant rather than retrieving the certificate from the PKCS11 interface where is was previously written (and where it would naturally reside permanently).

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by bryan-hunt** [comment]
\bot run checks

**Comment by alexa-noxon** [comment]
The spirit of this change was brought into master here with the merge of ECC608a + WinSim feature branch.
https://github.com/aws/amazon-freertos/commit/8a0968bc2c6699c5c8c0dc0e383466cfe3dd7783#diff-5ddbe5703615970ce07164e69e8e5010R622, where JITP certificate is retrieved from PKCS #11 module if the JITR certificate is blank in aws_clientcredential_keys.h. 

There is still work to be done to always retrieve a JITP/JITR certificate from PKCS #11, rather than only when it is not present in the header. 

Closing the PR.

Thanks for your help.

**Pull request closed without merging**
