### PR TITLE
AFR NimBLE: Add mbedTLS support as an option to Tinycrypt and few misc changes

### PR DESCRIPTION
**Pull request by prasad-alatkar**
AFR NimBLE: Add mbedTLS support as an option to Tinycrypt and few misc changes

Description
-----------

AFR NimBLE: Add mbedTLS support as an option to Tinycrypt

- Adds option to use mbedTLS instead of tinycrypt for crypto computations,
  includes changes related to NimBLE `ble_mesh` crypto as well.

AFR NimBLE: Fix misc warnings and return code in `ble_hs_tx_data`

- Previously `ble_hs_tx_data` returned 0 irrespective of error code returned by
  `ble_hci_trans_hs_acl_tx`.
- Minor changes in NimBLE stack to remove _discard const qualifier_ warnings.

AFR NimBLE: Misc changes in NimBLE porting layer and menuconfig option

- Minor fix to remove while loop & delay while transmitting data from
  host to controller.
- Add below menuconfig options:
  * To enable predefined public-private keypair for debugging (Vol. 3, Part H, 2.3.5.6.1).
  * To configure NimBLE stack size.
  * To enable/disable overriding tinycrypt with mbedTLS for crypto computations.

Checklist:
----------

- [ x] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by sarenameas** [comment]
Hello prasad-alatkar,

Our ESP-IDF version is copy of the official with small changes for FreeRTOS, which Espressif aids us in keeping up to date.
All ESP-IDF changes need to be directed to Espressif's official ESP-IDF repo: https://github.com/espressif/esp-idf

Thanks

**Comment by prasad-alatkar** [comment]
Hi @sarenameas, currently `nimble` is maintained as a component in AFR. This PR is intended to make `nimble` component in sync with `esp-idf`. CC @ravibhagavandas

**Comment by qiutongs** [comment]
We are testing this code change locally.

**Comment by sarenameas** [comment]
> Hi @sarenameas, currently `nimble` is maintained as a component in AFR. This PR is intended to make `nimble` component in sync with `esp-idf`. CC @ravibhagavandas

Apologies for my incorrect assumptions

**Comment by ravibhagavandas** [comment]
Build check using makefile failed for this PR.

/espressif/esp-idf/tools/kconfig/conf-idf --silentoldconfig /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/Kconfig
*
* Restart config...
*
*
* Enable NimBLE host stack
*
Enable NimBLE host stack (NIMBLE_ENABLED) [Y/n] y
  Maximum number of concurrent connections (NIMBLE_MAX_CONNECTIONS) [1] 1
  Maximum number of bonds to save across reboots (NIMBLE_MAX_BONDS) [3] 3
  Maximum number of CCC descriptors to save across reboots (NIMBLE_MAX_CCCDS) [10] 10
  Maximum number of connection oriented channels (NIMBLE_L2CAP_COC_MAX_NUM) [0] 0
  NimBLE Host task stack size (NIMBLE_TASK_STACK_SIZE) [4096] (NEW) aborted!

Console input/output is redirected. Run 'make oldconfig' to update configuration.


 Looks like the  new configs need to be added   to sdkconfig files at:
https://github.com/prasad-alatkar/amazon-freertos/tree/ble/NimBLE_misc_changes/vendors/espressif/boards/esp32/aws_demos
and
https://github.com/prasad-alatkar/amazon-freertos/tree/ble/NimBLE_misc_changes/vendors/espressif/boards/esp32/aws_tests

**Comment by prasad-alatkar** [comment]
Hi @ravibhagavandas Thank you for pointing out :D ...

**Comment by qiutongs** [comment]
@prasad-alatkar  It is better to not force push and just simply do normal commits. In that way, we can easily see the diff about what you changed since our last review.

**Comment by prasad-alatkar** [comment]
> @prasad-alatkar It is better to not force push and just simply do normal commits. In that way, we can easily see the diff about what you changed since our last review.

@qiutongs will take care of this here onward, thank you.

**Comment by qiutongs** [comment]
```
Enable NimBLE host stack (NIMBLE_ENABLED) [Y/n] y
  Maximum number of concurrent connections (NIMBLE_MAX_CONNECTIONS) [1] 1
  Maximum number of bonds to save across reboots (NIMBLE_MAX_BONDS) [3] 3
  Maximum number of CCC descriptors to save across reboots (NIMBLE_MAX_CCCDS) [10] 10
  Maximum number of connection oriented channels (NIMBLE_L2CAP_COC_MAX_NUM) [0] 0
  NimBLE Host task stack size (NIMBLE_TASK_STACK_SIZE) [4096] 4096
  Enable BLE Central role (NIMBLE_ROLE_CENTRAL) [Y/n] y
  Enable BLE Peripheral role (NIMBLE_ROLE_PERIPHERAL) [Y/n] y
  Enable BLE Broadcaster role (NIMBLE_ROLE_BROADCASTER) [Y/n] y
  Enable BLE Observer role (NIMBLE_ROLE_OBSERVER) [Y/n] y
  Persist the BLE Bonding keys in NVS (NIMBLE_NVS_PERSIST) [Y/n/?] y
  Security manager legacy pairing (NIMBLE_SM_LEGACY) [N/y/?] n
  Security manager secure connections (4.2) (NIMBLE_SM_SC) [Y/n/?] y
  Enable extra runtime asserts and host debugging (NIMBLE_DEBUG) [N/y/?] n
  Use predefined public-private key pair (NIMBLE_SM_SC_DEBUG_KEYS) [N/y/?] (NEW) aborted!
```

NIMBLE_SM_SC_DEBUG_KEYS also needs to be added into config

**Comment by qiutongs** [comment]
Plea

> ```
> Enable NimBLE host stack (NIMBLE_ENABLED) [Y/n] y
>   Maximum number of concurrent connections (NIMBLE_MAX_CONNECTIONS) [1] 1
>   Maximum number of bonds to save across reboots (NIMBLE_MAX_BONDS) [3] 3
>   Maximum number of CCC descriptors to save across reboots (NIMBLE_MAX_CCCDS) [10] 10
>   Maximum number of connection oriented channels (NIMBLE_L2CAP_COC_MAX_NUM) [0] 0
>   NimBLE Host task stack size (NIMBLE_TASK_STACK_SIZE) [4096] 4096
>   Enable BLE Central role (NIMBLE_ROLE_CENTRAL) [Y/n] y
>   Enable BLE Peripheral role (NIMBLE_ROLE_PERIPHERAL) [Y/n] y
>   Enable BLE Broadcaster role (NIMBLE_ROLE_BROADCASTER) [Y/n] y
>   Enable BLE Observer role (NIMBLE_ROLE_OBSERVER) [Y/n] y
>   Persist the BLE Bonding keys in NVS (NIMBLE_NVS_PERSIST) [Y/n/?] y
>   Security manager legacy pairing (NIMBLE_SM_LEGACY) [N/y/?] n
>   Security manager secure connections (4.2) (NIMBLE_SM_SC) [Y/n/?] y
>   Enable extra runtime asserts and host debugging (NIMBLE_DEBUG) [N/y/?] n
>   Use predefined public-private key pair (NIMBLE_SM_SC_DEBUG_KEYS) [N/y/?] (NEW) aborted!
> ```
> 
> NIMBLE_SM_SC_DEBUG_KEYS also needs to be added into config

**Comment by qiutongs** [comment]
Please make sure all the new config are added

NIMBLE_TASK_STACK_SIZE
NIMBLE_SM_SC_DEBUG_KEYS
NIMBLE_CRYPTO_STACK_MBEDTLS

**Comment by prasad-alatkar** [comment]
Hi @qiutongs sorry for the confusion, I have added the fix. Apart for this I have one point to add, we are in process to move AFR onto stable `esp-idf` release (CC: @mahavirj , @dhrishi ), so these changes will be included there as well.

**Comment by prasad-alatkar** [comment]
This PR can be closed in favor of : https://github.com/aws/amazon-freertos/pull/1443

**Pull request merged**
