### PR TITLE
PSoC64 pathes

### PR DESCRIPTION
**Pull request by CharleyChu**
Description
-----------
1. Fix IoT Taskpool unit test failure
2. vendor directory re-organize

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mingyue86010** [comment]
Should the folder "vendors/cypress/psoc6/psoc64tfm/COMPONENT_TFM_S_FW" also be moved to  "MTB" folder? 

The current PR has a post build process error which is caused by "/vendors/cypress/MTB/psoc6/psoc64tfm/COMPONENT_TFM_S_FW/tfm_s_unsigned.hex" cannot be found.

**Comment by CharleyChu** [comment]
yes, it should be. but it was filtered out by the .gitignore.

**Comment by mingyue86010** [comment]
> yes, it should be. but it was filtered out by the .gitignore.

Yeah.. Then can you also update the path in .gitignore file? It explicilty exclude tfm_s_unsigned.hex file.

**Comment by CharleyChu** [comment]
Yes, I did. it excludes all .hex file, except the tfm_s_unsigned.hex, but with wrong path.

**Pull request merged**
