### PR TITLE
Update documentation for BLE HAL

### PR DESCRIPTION
**Pull request by ravibhagavandas**
Update documentation for BLE HAL

Description
-----------
Update documentation for `ucChannelMap`  parameter in advertisement.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by lundinc2 — APPROVED** [review]

**Comment by mww-aws** [comment]
I think for the CBMC proofs you might need to rebase against main.

**Review by cobusve — APPROVED** [review]

**Pull request merged**
