### PR TITLE
CoAP support in Amazon FreeRTOS (#2390)

### PR DESCRIPTION
**Pull request by Mtalat**
CoAP support in Amazon FreeRTOS (#2390)

Description
-----------
CoAP support using LobaroCoAP libarary with a demo on stm32l475_discovery
* UDP option is added to  secure socket and to stm32l475_discovery wifi driver
* LobaroCoAP (https://github.com/lobaro/lobaro-coap) is added to 3rd-party libraries and to stm32l475_discovery
* Demo is created for coap client that sends a sample message (with ACK) to a coap server configured in FreeRTOSConfig.h

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by leegeth** [comment]
@Mtalat 

Thanks for your PR. Please see a list of few improvements/questions that came up as part of PR checks.

1. From the PR checks, I see that there are style checks that is failing. Would you be able to run the uncrustify to fix it?

You can follow the instructions below to run uncrustify

```
You may run the following command to repeat the check: python tools/git/hooks/src/pre_commit.py

You may run the following command to uncrustify staged files: python tools/git/hooks/src/pre_commit.py --uncrustify

You may run the following command to uncrustify a list of files: python tools/git/hooks/src/pre_commit.py --uncrustify <files>

You may run the following command to uncrustify all files: python tools/git/hooks/src/pre_commit.py --uncrustify-all-files
```

2. The PR build checks are failing because of the cmake builds. The way that the cmake builds are done in PR checks is that, cmake build is attempted for all the boards supported in this repository. Is it something that you are planning for with this PR or do you want this demo to be supported only on stm32l475_discovery board?

**Comment by Mtalat** [comment]
@leegeth 

Thank you for your reply. 

Regarding the style checks, we have  refactored the  code using uncrustify.
We are currently working on the cmake builds to make the demo supported on other boards.

**Comment by leegeth** [comment]
@Mtalat ,

Thanks for your contribution and your patience. As this PR brings a whole new library into our repository deserving a higher degree of scrutiny, and given the current team workload, you should expect a response from our reviewers no sooner than December 15th. Thanks for your understanding. Please let us know if you have any further questions or concerns.

**Comment by leegeth** [comment]
@Mtalat,
Thanks for your patience and contribution. Unfortunately, this PR cannot be merged to the repository, since the CoAP library added by this PR is not consistent with the quality criteria of our internally developed libraries. For example, please refer to the quality criteria that coreMQTT library has gone through as documented in the [README](https://github.com/FreeRTOS/coreMQTT#coremqtt-client-library).
We would like to express our gratitude in taking time to come up with this PR and showing us an example of providing CoAP support using an open source library. We are going to evaluate this proposal of providing CoAP support using an open source library in our repositories. 
In order to continue your application development with CoAP, you will be able to continue having this code in your fork. This may unblock you from your development using the CoAP library you brought in.
Please let us know if you have any follow up questions or concerns.

**Comment by leegeth** [comment]
@Mtalat,

We are closing the PR based on the latest comments posted about this change. Please let us know if you are having any questions or concerns.

**Pull request closed without merging**
