### PR TITLE
Remove all Kernel and TCP CBMC proofs from this repository

### PR DESCRIPTION
**Pull request by AniruddhaKanhere**
Description
-----------
Removed the proofs for Kernel and +TCP.

Checklist:
----------

- [X] I have tested my changes. No regression in existing tests.
- [X] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nateglims** [comment]
This will need to be rebased after #3161 or manually inspected that no AWS credentials are added by the final approver.

**Review by markrtuttle — APPROVED** [review]

**Review by cobusve — APPROVED** [review]

**Pull request merged**
