### PR TITLE
Rename aws_application_version.h to iot_application_version.h

### PR DESCRIPTION
**Pull request by paulbartell**
Rename aws_application_version.h to iot_application_version.h

Description
-----------
Rename aws_application_version.h to iot_application_version.h since this file is not necessarily AWS related.

Checklist:
----------
- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aggarw13** [comment]
Seems like there is a submodule update for the FreeRTOS+TCP library in the change set. Is that an intended part of the change?

**Comment by paulbartell** [comment]
@aggarw13 Yes. The submodule update is intentional, since one of the files in that repo references aws_application_version.h. 

It seems odd for there to be this type of dependency. Working that out with @AniruddhaKanhere in the PR over here: https://github.com/FreeRTOS/FreeRTOS-Plus-TCP/pull/188

**Pull request closed without merging**
