### PR TITLE
Add ACL state changed callback

### PR DESCRIPTION
**Pull request by doujiahu**
Add ACL state changed callback

Description
-----------
Add ACL state changed callback and corresponding reason codes

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ravibhagavandas** [comment]
The builds are failing as `pxDisable()` API is called with an argument `0` from the tests here:
https://github.com/aws/amazon-freertos/blob/a126b0c55795be5986f86d4f6ef73bc5ed091c29/libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_integration.c#L299
https://github.com/aws/amazon-freertos/blob/1ce87a27d5993b5521e9f180bb975ababb52ad41/libraries/abstractions/ble_hal/test/src/iot_test_ble_hal_common.c#L578

Could you fix them ?

**Comment by doujiahu** [comment]
ACE required all functions that do not take paramters to explictly have (void).
pxDisable shouldn't have any parameter, would you like me to fix the test case?

**Comment by ravibhagavandas** [comment]
> 
> 
> ACE required all functions that do not take paramters to explictly have (void).
> pxDisable shouldn't have any parameter, would you like me to fix the test case?

Yes I agree. You can go ahead and fix this.

**Review by cobusve — APPROVED** [review]

**Review by ravibhagavandas — APPROVED** [review]

**Pull request merged**
