### PR TITLE
PR #2: Fix demo, test project after updating device driver

### PR DESCRIPTION
**Pull request by VanNamDinh**
Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by abhidixi11** [comment]
Hello @ VanNamDinh  Can you please resolve the conflicts, PR#1 is already merged, this PR is approved as well, but conflicts need to be resolved.

**Comment by VanNamDinh** [comment]
> Hello @VanNamDinh Can you please resolve the conflicts, PR#1 is already merged, this PR is approved as well, but conflicts need to be resolved.

Hello @abhidixi11 . I have just resolved all conflicts.

**Comment by abhidixi11** [comment]
Thanks @VanNamDinh , I'll try to get it in by tomorrow.

**Comment by abhidixi11** [comment]
@VanNamDinh , Looks like it may not be rebased with the master that is failing the build. It could be because we have merged #1

**Pull request merged**
