### PR TITLE
Fix build failure for TI tests for cmake

### PR DESCRIPTION
**Pull request by aggarg**
Description
-----------

The Ninja generator combines linker and post build commands using '&&'
which results in a long string. Windows has a limit of 8191 characters
on the command line string length. We were hitting that limit for TI and
were getting "command string too long" error.

This commit updates the cmake files to force Ninja to use response files
which is a feature implemented for exactly this purpose and results in a
much smaller command string.

Signed-off-by: Gaurav Aggarwal <aggarg@amazon.com>

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by tgsong** [comment]
Can you also add some comments in cmake file explaining why this can't be done in the `arm-ti.cmake` file? Also we need to delete the same setting in that file (`set(CMAKE_C_RESPONSE_FILE_LINK_FLAG "")`).

**Comment by aggarg** [comment]
> 
> 
> Can you also add some comments in cmake file explaining why this can't be done in the `arm-ti.cmake` file? Also we need to delete the same setting in that file (`set(CMAKE_C_RESPONSE_FILE_LINK_FLAG "")`).

Added comment. We cannot remove the line mentioned above from `arm-ti.cmake` as the TI archiver starts to fault when I do that.

**Pull request closed without merging**
