### PR TITLE
FreeRTOS_DNS : changes to make asynchronous lookup work, version 4

### PR DESCRIPTION
**Pull request by htibosch**
Description
-----------
This PR replaces [#1195](https://github.com/aws/amazon-freertos/pull/1195).
That PR had merging problems and it was hard to get it rebased.

My GIT client ( SmartGit ) has problems switching between old and new branches, since `/freertos_kernel` has become a link to a different repo.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

Oops, I automatically filled in two crosses [x]. The patch was tested within the earlier repo, not yet in the latest ( ever-changing ) release of software. I will test the change on both PC and an ST board.

Hein

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by qiutongs** [comment]
There are CBMC changes included in this PR. Is that intended?

**Comment by htibosch** [comment]
> There are CBMC changes included in this PR. Is that intended?

Yes, that is intended. I took them from the earlier PR #1195. I hope that they're still in sync with the current sources.

Testing progress: I just tested it on an STM32F4x, which went all well. Now I'll test it with the WinSim project.

**Comment by htibosch** [comment]
In a meanwhile, I tested the changes on both an STM32F4 and in the "WinSim" project.
I tested both with and without `ipconfigDNS_USE_CALLBACKS` and `ipconfigUSE_LLMNR`.

I found one problem in the WinSim project, which is not related to this patch: `SYSTEM_Init()` crashed when called from `vApplicationIPNetworkEventHook()`. It was solved by calling `SYSTEM_Init()` before starting the scheduler. See also issue [#1404](https://github.com/aws/amazon-freertos/issues/1404)

> Build check on Windows - Build finished. 32 tests run, 0 skipped, 3 failed.
> error LNK2019: unresolved external symbol _ulDNSHandlePacket

The testing module `iot_test_freertos_tcp.c` calls `ulDNSHandlePacket()` that was not compiled because of a different configuration ( FreeRTOSIPConfig.h ).

I have made a change, from now on `ulDNSHandlePacket()` will always be compiled.

Hein

**Comment by htibosch** [comment]
About the commit "Let unsigned identifiers start with a 'u'":

In the original patch, `BaseType_t` was replaced by `size_t` or `TickType_t` wherever appropriate. In the latest commit I changed the identifiers accordingly, e.g.:

~~~c
size_t uxBufferLength;
TickType_t uxTimeout;
~~~

Tested again, now on a Xilinx Zynq.

**Pull request merged**
