### PR TITLE
Add Cypress code for psoc64 ES100 production board.

### PR DESCRIPTION
**Pull request by mingyue86010**
- This commit packaged the commits from feature/psoc64 branch upto "Further pruning vendor files" (PR #2052: https://github.com/aws/amazon-freertos/pull/2052).
- This commit fixed the problem that revert changing the code on master, which is caused by a "-f" push on feature/psoc64 branch.
- All the furture change to feature/psoc64 branch (After the commit "Fixed revert change to the code from master") shloud be cherry-picked to this branch for the preparation of merging to master.

Description
-----------

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by cobusve** [comment]
Please ensure that we resolve the location of the OTA code fully before we merge this PR.

**Comment by mingyue86010** [comment]
> I am going to leave a Request Changes here to ensure all PRBR's are aware of the OTA requirement

OTA has been removed from the PR. Jenkins tests:

Cmake demos: https://amazon-freertos-ci.corp.amazon.com/view/Beta%20Jobs/job/im_beta/job/nightly_custom_cmake/227/
IDE demos: https://amazon-freertos-ci.corp.amazon.com/view/Beta%20Jobs/job/im_beta/job/nightly_custom_ide/203/
Cmake tests: https://amazon-freertos-ci.corp.amazon.com/view/Beta%20Jobs/job/im_beta/job/nightly_custom_cmake/229/

We just need verify the code are able to build and no new failure were introduced by removing the OTA. ( Some tests might be skipped due to the serial port issue. )

**Comment by mingyue86010** [comment]
Cherry picked "Update ota config file for Cypress psoc64 board to fix the build error." from feature/psoc64. This won't affect this PR since OTA is disabled.

**Comment by mingyue86010** [comment]
https://amazon-freertos-ci.corp.amazon.com/view/Beta%20Jobs/job/im_beta/job/nightly_custom_ide/203/

The Jenkins  job above reported SUCCESS for IDE aws_demos project, but the consloe output actually shows build failure... The build problem has been fixed by last commit (74446f6). The latest test result is here: https://amazon-freertos-ci.corp.amazon.com/view/Beta%20Jobs/job/im_beta/job/nightly_custom_ide/205/

**Pull request merged**
