### PR TITLE
vendors/espressif: upgrade ESP-IDF to v3.1.5 release

### PR DESCRIPTION
**Pull request by mahavirj**
Description
-----------

Upgrade ESP-IDF to v3.1.5 release
Release notes at: https://github.com/espressif/esp-idf/releases/tag/v3.1.5

Checklist:
----------

 - [X] I have tested my changes. No regression in existing tests.
 - [X] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by aggarg** [comment]
@mahavirj The Linux build fails with the following error:

```
====================================================================================================
Building project: vendors/espressif/boards/esp32
====================================================================================================
make: Entering directory '/var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/boards/esp32/aws_demos'
make[1]: Entering directory '/var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig'
cc -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP  /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/mconf.c -o mconf.o
flex -L -Pzconf -ozconf.lex.c /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/zconf.l
bison -t -l -p zconf -o zconf.tab.c /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/zconf.y
sed -E "s/\\x0D$//" /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/zconf.gperf | gperf -t --output-file zconf.hash.c -a -C -E -g -k '1,3,$' -p -t
cc -I /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP  zconf.tab.c -o zconf.tab.o
/var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/lxdialog/check-lxdialog.sh -check cc  -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP -lncursesw -ltinfo
cc -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP  /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/lxdialog/checklist.c -o lxdialog/checklist.o
cc -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP  /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/lxdialog/util.c -o lxdialog/util.o
cc -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP  /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/lxdialog/inputbox.c -o lxdialog/inputbox.o
cc -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP  /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/lxdialog/textbox.c -o lxdialog/textbox.o
cc -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP  /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/lxdialog/yesno.c -o lxdialog/yesno.o
cc -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP  /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/lxdialog/menubox.c -o lxdialog/menubox.o
cc -o mconf-idf mconf.o zconf.tab.o lxdialog/checklist.o lxdialog/util.o lxdialog/inputbox.o lxdialog/textbox.o lxdialog/yesno.o lxdialog/menubox.o -lncursesw -ltinfo
cc -c  -D_GNU_SOURCE -D_DEFAULT_SOURCE -I/usr/include/ncursesw -DCURSES_LOC="<ncurses.h>" -DNCURSES_WIDECHAR=1 -DLOCALE -MMD -MP  /var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig/conf.c -o conf.o
cc -o conf-idf conf.o  zconf.tab.o -lncursesw -ltinfo
make[1]: Leaving directory '/var/jenkins/workspace/afr_pr_build_linux/vendors/espressif/esp-idf/tools/kconfig'
GENCONFIG
*
* Restart config...
*
*
* Bluetooth
*
Bluetooth (BT_ENABLED) [Y/n/?] y
  BR/EDR Sync(SCO/eSCO) default data path
    1. HCI (BTDM_CONTROLLER_BR_EDR_SCO_DATA_PATH_HCI) (NEW)
  > 2. PCM (BTDM_CONTROLLER_BR_EDR_SCO_DATA_PATH_PCM) (NEW)
  choice[1-2?]: aborted!

Console input/output is redirected. Run 'make oldconfig' to update configuration.
```

Would you please take a look.

Thanks.

**Comment by mahavirj** [comment]
@aggarg Added subsequent commit and tested using following,

```
make -j8 -C vendors/espressif/boards/esp32/aws_demos/ clean
make -j8 -C vendors/espressif/boards/esp32/aws_demos/
make -j8 -C vendors/espressif/boards/esp32/aws_tests/ clean
make -j8 -C vendors/espressif/boards/esp32/aws_tests/
```

**Pull request merged**
