### PR TITLE
Let Socket_t and SocketSet_t point to a struct

### PR DESCRIPTION
**Pull request by htibosch**
FreeRTOS+TCP : Let the `Socket_t` and `SocketSet_t` point to a struct in stead of void

Description
-----------
In earlier days, the actual contents of objects types was often obfuscated by making them void pointers.
Within the libraries, the `void *` would be casted to the real object type. That is where lint starts complaining, e.g. here:

~~~c
void FreeRTOS_FD_SET( Socket_t xSocket, SocketSet_t xSocketSet, EventBits_t xSelectBits )
{
FreeRTOS_Socket_t *pxSocket = ( FreeRTOS_Socket_t * ) xSocket;
SocketSelect_t *pxSocketSet = ( SocketSelect_t * ) xSocketSet;
~~~

Lint doesn't like the cast from `void *` to 'struct *`.

It would be nice when the anonymous types `Socket_t` and `SocketSet_t` point to "a struct".

I propose the following changes:

~~~c
 /* The socket type itself. */
-typedef void *Socket_t;
+struct xSOCKET;
+typedef struct xSOCKET *Socket_t;

 /* The SocketSet_t type is the equivalent to the fd_set type used by the
 Berkeley API. */
-typedef void *SocketSet_t;
+struct xSOCKET_SET;
+typedef struct xSOCKET_SET *SocketSet_t;
~~~

Note that the higher-level header file `iot_secure_sockets.h` has copied the definition of Socket_t, so it should be adapted as well:

~~~c
-typedef void * Socket_t;
+struct xSOCKET;
+typedef struct xSOCKET *Socket_t;
~~~

After the change, the compiler showed me that in a few locations, a cast had an unnecessary asterisk:

~~~c
-pxSocket->u.xTCP.pxHandleSent( ( Socket_t * )pxSocket, ulCount );
+pxSocket->u.xTCP.pxHandleSent( ( Socket_t )pxSocket, ulCount );
~~~

The compiler doesn't care about the difference between a `void*` and a `void**`.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
I tested using the Microchip demo as well as the demo on Windows.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by htibosch** [comment]
PS. in iot_secure _sockets.c I propose a few casts, partly related to the patch:

~~~c
-    pxContext = SOCKETS_INVALID_SOCKET;
+    pxContext = ( SSOCKETContextPtr_t ) SOCKETS_INVALID_SOCKET;
~~~

`SOCKETS_INVALID_SOCKET` used to be a void pointer, which could be assigned `SSOCKETContextPtr_t`.
After the change, the compiler would complain about mixing pointers to different structs.

**Comment by htibosch** [comment]
> uncrustify failed. Please run it manually and resubmit the PR

Does anyone know which of the 7 files made uncrustify fail?

It should be noted that the sources under `freertos_plus_tcp` have never been completely uncrustified yet, and also that those sources have a slightly different ( FreeRTOS ) [coding style](https://github.com/aws/amazon-freertos/blob/master/libraries/freertos_plus/standard/freertos_plus_tcp/uncrustify.cfg).

I don't mind applying it, but preferably in a separate PR. Thanks, Hein

**Comment by htibosch** [comment]
About the commit "Socket_t and SocketSet_t : uncrustified" :
Uncrustify proposes this change in iot_secure_sockets.h.
I would be happy to uncrustify all FreeRTOS+TCP sources as well, but I'd rather do that in a separate PR, agreed?
Hein

**Comment by markrtuttle** [comment]
Patch contained in https://github.com/markrtuttle/amazon-freertos/tree/tibosch2-tuttle

**Comment by dan4thewin** [comment]
Here's part of the log for the failed windows build.
```
====================================================================================================
Building project: vendors\nxp\boards\lpc54018iotmodule
====================================================================================================

     IAR Command Line Build Utility V8.2.2.5792
     Copyright 2002-2018 IAR Systems AB.

Building configuration: aws_demos - Debug
[...]
iot_secure_sockets.c 
C:\Jenkins\workspace\afr_pr_build_win\vendors\nxp\boards\lpc54018iotmodule\ports\secure_sockets\iot_secure_sockets.c(224) : Error[Pe042]: operand types are incompatible ("Socket_t" and "SSOCKETContextPtr_t")
C:\Jenkins\workspace\afr_pr_build_win\vendors\nxp\boards\lpc54018iotmodule\ports\secure_sockets\iot_secure_sockets.c(264) : Error[Pe042]: operand types are incompatible ("Socket_t" and "SSOCKETContextPtr_t")
C:\Jenkins\workspace\afr_pr_build_win\vendors\nxp\boards\lpc54018iotmodule\ports\secure_sockets\iot_secure_sockets.c(395) : Error[Pe042]: operand types are incompatible ("Socket_t" and "SSOCKETContextPtr_t")
C:\Jenkins\workspace\afr_pr_build_win\vendors\nxp\boards\lpc54018iotmodule\ports\secure_sockets\iot_secure_sockets.c(487) : Error[Pe042]: operand types are incompatible ("Socket_t" and "SSOCKETContextPtr_t")
C:\Jenkins\workspace\afr_pr_build_win\vendors\nxp\boards\lpc54018iotmodule\ports\secure_sockets\iot_secure_sockets.c(633) : Error[Pe042]: operand types are incompatible ("Socket_t" and "SSOCKETContextPtr_t")
C:\Jenkins\workspace\afr_pr_build_win\vendors\nxp\boards\lpc54018iotmodule\ports\secure_sockets\iot_secure_sockets.c(722) : Error[Pe513]: a value of type "Socket_t" cannot be assigned to an entity of type "SSOCKETContextPtr_t"
C:\Jenkins\workspace\afr_pr_build_win\vendors\nxp\boards\lpc54018iotmodule\ports\secure_sockets\iot_secure_sockets.c(725) : Error[Pe120]: return value type ("SSOCKETContextPtr_t") does not match the function type ("Socket_t")
Error while running C/C++ Compiler
```

**Comment by htibosch** [comment]
To @dan4thewin : thanks for checking the patch on a lpc54018 board with an IAR compiler.

I made some changes:

A pointer to `SSOCKETContext_t` can not be compared with a pointer to `xSOCKET` (`Socket_t`), thus I introduced a new:

~~~c
#define SOCKETS_INVALID_CONTEXT        ( ( SSOCKETContextPtr_t ) ~0U )
~~~

which has the same value as the existing defines:

~~~c
#define SOCKETS_INVALID_SOCKET         ( ( Socket_t ) ~0U )
#define FREERTOS_INVALID_SOCKET        ( ( Socket_t ) ~0U )
~~~

Unfortunately I do not have the proper compilers installed to test these changes.
Thanks, Hein

**Comment by htibosch** [comment]
Sorry, I changed too much code in lpc54018 / iot_secure_sockets.c. It triggered a build check error.

Now undoing the change for line 359:

~~~c
-    if( ( SOCKETS_INVALID_CONTEXT != xSocket ) &&
+    if( ( SOCKETS_INVALID_SOCKET != xSocket ) &&
~~~

**Pull request merged**
