### PR TITLE
Uncrustify all source files in the repo

### PR DESCRIPTION
**Pull request by aggarg**
Description
-----------
Given that the code style check is now a mandatory check for every PR,
we need to make sure that all the files are uncrustified.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by htibosch** [comment]
@sarenameas , thanks for doing this.
I'm glad you did not apply it to the FreeRTOS kernel, or the FreeRTOS+TCP sources,
As you must have noticed, I checked in a special version of [uncrustify.cfg](https://github.com/aws/amazon-freertos/blob/master/libraries/freertos_plus/standard/freertos_plus_tcp/uncrustify.cfg) that preserves the FreeRTOS coding style ( that uses tabs ).
I don't mind applying it to the FreeRTOS+TCP sources later on.
Hein

**Comment by aggarg** [comment]
> 
> 
> @sarenameas , thanks for doing this.
> I'm glad you did not apply it to the FreeRTOS kernel, or the FreeRTOS+TCP sources,
> As you must have noticed, I checked in a special version of [uncrustify.cfg](https://github.com/aws/amazon-freertos/blob/master/libraries/freertos_plus/standard/freertos_plus_tcp/uncrustify.cfg) that preserves the FreeRTOS coding style ( that uses tabs ).
> I don't mind applying it to the FreeRTOS+TCP sources later on.
> Hein

Thanks Hein. Yes we have excluded FreeRTOS and FreeRTOS+TCP code. You can check the excluded files here: https://github.com/aws/amazon-freertos/pull/946

Are you saying that you would apply the same config file to FreeRTOS+TCP source code or do you want to apply the special config which preserves tabs?

Thanks.

**Comment by htibosch** [comment]
@aggarg 

> Are you saying that you would apply the same config file to
> FreeRTOS+TCP source code or do you want to apply the special
> config which preserves tabs?

I think I don't really have a say in this, but for FreeRTOS+TCP, it would be my preference to preserve the old style with its tabs, indentations, and comment style. That is why I checked in this [uncrustify.cfg](https://github.com/aws/amazon-freertos/blob/master/libraries/freertos_plus/standard/freertos_plus_tcp/uncrustify.cfg). Thanks.

**Comment by aggarg** [comment]
@htibosch Alright, let's use the old config as of now. 

Thanks.

**Pull request merged**
