### PR TITLE
- Updated CAL to latest v3.2.5 and tested aws_demo and aws_test project

### PR DESCRIPTION
**Pull request by RathanChandavathR**
Updated CAL to latest v3.2.5 and tested aws_demo and aws_test project

### CODE REVIEW

**Comment by lundinc2** [comment]
Hi @chandavath,
Are you able to see the cause of the build failures? Or shall I send you a ZIP file of the output?

Thanks,

Carl

**Comment by chandavath** [comment]
Hi @lundinc2,

I have fixed the issue. Let's see build reports. 


Thanks, 
Rathan.

**Comment by paulbartell** [comment]
Closing this PR. Cryptoauthlib update wiill be handled in #3200

**Pull request closed without merging**
