### PR TITLE
Synopsys ARC port. Add basic support to Synopsys ARC processors and boards

### PR DESCRIPTION
**Pull request by YuguoWH**
Description
-----------
This is a port from Synopsys ARC to AWS, the  port is based on [Synopsys embARC BSP](https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_bsp/tree/upstream)
It requires [ARC port to FreeRTOS-Kernel](https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/8) to work

The supported cores are ARC EM and HS series
The supported boards are EMSDP, EMSK, HSDK and IoTDK (with default cores)

Limits and Issues:
-----------

- This is a basic port which only have console and Kernel ported. Currently the boards do not have WiFi and BLE modules. 
- It uses cmake ExternalProject_Add() to pull embARC BSP code and then patch on it. Therefore it could have some git problems if embARC BSP have updates in the future. 

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lundinc2** [comment]
Hi @YuguoWH,

It has now been some time since this was opened. Was your intention to have this PR be in a draft state? Is this still work in progress?

**Comment by YuguoWH** [comment]
Hi @lundinc2 , it is my intention to keep this PR as a draft because our boards have no on-board wifi/ble modules. I'm actually not sure if these boards are acceptable to AWS-freertos. Do you have any advice on this?
Another reason to keep this a draft is that it relies on arc porting code in FreeRTOS-Kernel. I have submitted some PR to FreeRTOS-Kernel to add support of ARC cores and those PR have merged already.

**Comment by lundinc2** [comment]
@YuguoWH thanks for providing the update. I will see about this requirement and get back to you

**Comment by YuguoWH** [comment]
Hi, @lundinc2, do you have any news about the requirements? thanks.

**Comment by lundinc2** [comment]
Hi @YuguoWH,

This repository will host boards that have some kind of network connectivity that supports connecting to AWS IoT Core.

You may add a port to the FreeRTOS Kernel here https://github.com/FreeRTOS/FreeRTOS-Kernel and you may add a demo for your board in this repository https://github.com/FreeRTOS/FreeRTOS.

My understanding is that the kernel port is already merged, so a demo could be added to FreeRTOS/FreeRTOS>

Thanks,

Carl

**Comment by YuguoWH** [comment]
@lundinc2 Thanks Carl, I guess I should close this PR then.

**Pull request closed without merging**
