### PR TITLE
Support for dynamic credential switching

### PR DESCRIPTION
**Pull request by KazukiMochizuki926**
Description
-----------
Supports dynamic credential switching.
Fleet Provisioning uses the claim certificate and private key to connect to AWS the first time, and then uses the device-specific claim certificate and private key to connect to AWS next time.
However, the current FreeRTOS library cannot support Fleet Provisioning because it uses fixed credential information.
Therefore, the FreeRTOS library source code has been updated to allow dynamic credential switching.
The IDT test items FullSecureSockets, FullTLS, and FulMQTT have passed.

idt_1
idt_2
idt_3

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by jasonpcarroll** [comment]
Hi @KazukiMochizuki926,
Thank you for your contribution! I've started the CI checks and will review.
Best.
Jason Carroll

**Comment by cobusve** [comment]
Hey all, I took a closer look a this one and we need to take a bit of change of direction here. I think making all these modules dependent on the list of credentials leaks this change into too many places. 

I think we should change this to pass the credentials into all the modules and have the list in a single place, that will not require all of these modules to be updated with this dependency which will cause all kinds of problems later on.

Also can we please move this effort to the FreeRTOS/FreeRTOS location where the new code is located?

**Pull request closed without merging**
