### PR TITLE
Move Xilinx network driver files from vendor directory to FreeRTOS+TCP portable/NetworkInterface directory.

### PR DESCRIPTION
**Pull request by yuhui-zheng**
Move Xilinx network driver files from vendor directory to FreeRTOS+TCP portable/NetworkInterface directory.

Description
-----------
See discussion and rationale under this PR -- https://github.com/aws/amazon-freertos/pull/1628.

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yuhui-zheng** [comment]
@htibosch I cannot assign this PR to you, but you may be the right person to review this PR...

**Comment by htibosch** [comment]
> @htibosch I cannot assign this PR to you, but you may be the right person to review this PR...

@yuhui-zheng: thank you for this PR, I think it's the best location. I tested both the demos and tests projects by compiling them in a fresh workspace.

Linking gives an error ( parameters too long ), but that can be avoided by changing the project's make command to: `make.exe SHELL=C:\Windows\System32\cmd.exe` ( see [issue 1555](https://github.com/aws/amazon-freertos/issues/1555#issuecomment-562835276) )

But I still don't understand why these directories occur twice, each with the same contents:

    vendors/xilinx/boards/microzed/aws_demos/application_code/xilinx_code
    vendors/xilinx/boards/microzed/aws_tests/application_code/xilinx_code

I would recommend merging them into e.g.

    vendors/xilinx/boards/microzed/xilinx_code

**Comment by yuhui-zheng** [comment]
@htibosch Thank you, will forward this comment to a colleague who's currently working on this port.

**Pull request merged**
