### PR TITLE
Update Espressif port for OTA

### PR DESCRIPTION
**Pull request by divekarshubham**
Update Espressif port for OTA

Description
-----------

* Revert cleanup to OTA PAL after esp-idf 4.2 update. Since the functions seem to have an error while writing to an offset in the flash
* Add the functions back to `aws_esp_ota_ops.c` which help write to flash. Using these functions in the `ota_pal` instead of the ones in `esp_ota_ops.c`

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by pvyawaha — COMMENTED** [review]
@mahavirj  @shubhamkulkarni97 can you please review these changes as it was breaking the espressif port.

**Comment by mahavirj** [comment]
@divekarshubham 

> Revert cleanup to OTA PAL after esp-idf 4.2 update. Since the functions seem to have an error while writing to an offset in the flash

Can you please update on the error here? I think our v4.2/v4.2.1 updates were both qualified for all tests including OTA.

**Comment by divekarshubham** [comment]
> @divekarshubham
> 
> > Revert cleanup to OTA PAL after esp-idf 4.2 update. Since the functions seem to have an error while writing to an offset in the flash
> 
> Can you please update on the error here? I think our v4.2/v4.2.1 updates were both qualified for all tests including OTA.

Copying over the error from PR https://github.com/aws/amazon-freertos/pull/3155

```
Re-enable cpu cache.
Guru Meditation Error: Core  0 panic'ed (Cache disabled but cached memory region accessed). 
Core  0 register dump:
PC      : 0x4000c310  PS      : 0x00060834  A0      : 0x8009dcac  A1      : 0x3ffe9550 
A2      : 0x3ffe9560  A3      : 0x400c2000  A4      : 0x00000004  A5      : 0x3ffe9560 
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x00000000  A9      : 0x3ffe94e0 
A10     : 0x00000000  A11     : 0x00000001  A12     : 0x3ff42000  A13     : 0x3ffe9521 
A14     : 0x00000000  A15     : 0x00000001  SAR     : 0x00000020  EXCCAUSE: 0x00000007 
EXCVADDR: 0x00000000  LBEG    : 0x4000c2e0  LEND    : 0x4000c2f6  LCOUNT  : 0xffffffff 
Backtrace:0x4000c30d:0x3ffe9550 0x4009dca9:0x3ffe9560 0x4009e681:0x3ffe95a0 0x4009e9d7:0x3ffe95c0 0x400842ac:0x3ffe95e0 0x4011f02f:0x3ffe9630 0x4011e9d5:0x3ffe9650 0x400d5607:0x3ffe9670 0x400de28d:0x3ffe9690 0x400dfcb5:0x3ffe96c0 0x400dfd29:0x3ffe96f0 0x400deca3:0x3ffe9740 0x400ded56:0x3ffe9770 0x400ded75:0x3ffe97a0 0x400d61fe:0x3ffe97c0 0x40090011:0x3ffe97e0
0x4009dca9: spi_flash_ll_set_buffer_data at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../vendors/espressif/esp-idf/components/soc/src/esp32/include/hal/spi_flash_ll.h:185
 (inlined by) spi_flash_ll_program_page at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../vendors/espressif/esp-idf/components/soc/src/esp32/include/hal/spi_flash_ll.h:203
 (inlined by) spi_flash_hal_program_page at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../vendors/espressif/esp-idf/components/soc/src/hal/spi_flash_hal_iram.c:47
0x4009e681: spi_flash_chip_generic_page_program at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../vendors/espressif/esp-idf/components/spi_flash/spi_flash_chip_generic.c:173
0x4009e9d7: spi_flash_chip_generic_write at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../vendors/espressif/esp-idf/components/spi_flash/spi_flash_chip_generic.c:195
0x400842ac: esp_flash_write at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../vendors/espressif/esp-idf/components/spi_flash/esp_flash_api.c:616
0x4011f02f: esp_partition_write at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../vendors/espressif/esp-idf/components/spi_flash/partition.c:389
0x4011e9d5: esp_ota_write_with_offset at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../vendors/espressif/esp-idf/components/app_update/esp_ota_ops.c:283
0x400d5607: otaPal_WriteBlock at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../vendors/espressif/boards/ports/ota_pal_for_aws/ota_pal.c:587
0x400de28d: processDataBlock at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../libraries/ota_for_aws/source/ota.c:2515
0x400dfcb5: ingestDataBlock at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../libraries/ota_for_aws/source/ota.c:2714
0x400dfd29: processDataHandler at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../libraries/ota_for_aws/source/ota.c:1185
0x400deca3: executeHandler at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../libraries/ota_for_aws/source/ota.c:2816
0x400ded56: receiveAndProcessOtaEvent at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../libraries/ota_for_aws/source/ota.c:2893
0x400ded75: OTA_EventProcessingTask at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../libraries/ota_for_aws/source/ota.c:2918
0x400d61fe: prvOTAAgentTask at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../demos/ota/ota_demo_core_mqtt/ota_demo_core_mqtt.c:1643
0x40090011: vPortTaskWrapper at /Users/shubhamkulkarni/forkedafr/amazon-freertos/build/../freertos_kernel/portable/ThirdParty/GCC/Xtensa_ESP32/port.c:154
```

The following tests also fail with the mainline:
* otaPal_CloseFile_ValidSignature
* otaPal_CheckFileSignature_ValidSignature
* otaPal_CloseFile_ValidSignatureKeyInFlash

**Comment by mahavirj** [comment]
@divekarshubham 

> The following tests also fail with the mainline:

Mainline is after your migration changes for OTA v3, so I expect that to fail.

Quick review suggest that ordering of arguments to API `esp_ota_write_with_offset` looks incorrect after your changes.

Previous reference after IDF v4.2.1 integration:

https://github.com/aws/amazon-freertos/blob/e2a614f4d932c505ef091a5ca1e3393841c2601d/vendors/espressif/boards/ports/ota/aws_ota_pal.c#L565

After your changes:

https://github.com/aws/amazon-freertos/blob/41471b7968f27bd292710d51c5cfa672f688d876/vendors/espressif/boards/ports/ota_pal_for_aws/ota_pal.c#L572

Can you please check this once? Please note that, there are 2 such occurrences of this API usage, please fix both and try once.

**Comment by pvyawaha** [comment]
> @divekarshubham
> 
> > The following tests also fail with the mainline:
> 
> Mainline is after your migration changes for OTA v3, so I expect that to fail.
> 
> Quick review suggest that ordering of arguments to API `esp_ota_write_with_offset` looks incorrect after your changes.
> 
> Previous reference after IDF v4.2.1 integration:
> 
> https://github.com/aws/amazon-freertos/blob/e2a614f4d932c505ef091a5ca1e3393841c2601d/vendors/espressif/boards/ports/ota/aws_ota_pal.c#L565
> 
> After your changes:
> 
> https://github.com/aws/amazon-freertos/blob/41471b7968f27bd292710d51c5cfa672f688d876/vendors/espressif/boards/ports/ota_pal_for_aws/ota_pal.c#L572
> 
> Can you please check this once? Please note that, there are 2 such occurrences of this API usage, please fix both and try once.

Thank you @mahavirj , @divekarshubham can you please test with these and review if any other changes got in ?

**Comment by divekarshubham** [comment]
> @divekarshubham
> 
> > The following tests also fail with the mainline:
> 
> Mainline is after your migration changes for OTA v3, so I expect that to fail.
> 
> Quick review suggest that ordering of arguments to API `esp_ota_write_with_offset` looks incorrect after your changes.
> 
> Previous reference after IDF v4.2.1 integration:
> 
> https://github.com/aws/amazon-freertos/blob/e2a614f4d932c505ef091a5ca1e3393841c2601d/vendors/espressif/boards/ports/ota/aws_ota_pal.c#L565
> 
> After your changes:
> 
> https://github.com/aws/amazon-freertos/blob/41471b7968f27bd292710d51c5cfa672f688d876/vendors/espressif/boards/ports/ota_pal_for_aws/ota_pal.c#L572
> 
> Can you please check this once? Please note that, there are 2 such occurrences of this API usage, please fix both and try once.

Thanks for pointing this out, this fix is working for our tests. Pushing out a PR for this fix.

**Comment by divekarshubham** [comment]
> @divekarshubham
> 
> > The following tests also fail with the mainline:
> 
> Mainline is after your migration changes for OTA v3, so I expect that to fail.
> 
> Quick review suggest that ordering of arguments to API `esp_ota_write_with_offset` looks incorrect after your changes.
> 
> Previous reference after IDF v4.2.1 integration:
> 
> https://github.com/aws/amazon-freertos/blob/e2a614f4d932c505ef091a5ca1e3393841c2601d/vendors/espressif/boards/ports/ota/aws_ota_pal.c#L565
> 
> After your changes:
> 
> https://github.com/aws/amazon-freertos/blob/41471b7968f27bd292710d51c5cfa672f688d876/vendors/espressif/boards/ports/ota_pal_for_aws/ota_pal.c#L572
> 
> Can you please check this once? Please note that, there are 2 such occurrences of this API usage, please fix both and try once.

Thanks for pointing this out, this fix is working for our tests. Pushing out a PR for this fix.

**Pull request closed without merging**
