### PR TITLE
[DRAFT/Not to be merged] Test submodule project impact

### PR DESCRIPTION
**Pull request by AniruddhaKanhere**
Description
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by feliperodri** [comment]
@AniruddhaKanhere while you work on this PR, could you convert it to draft? We're getting spurious alarms over CBMC proof failures.

**Comment by AniruddhaKanhere** [comment]
> @AniruddhaKanhere while you work on this PR, could you convert it to draft? We're getting spurious alarms over CBMC proof failures.

I apologise. I have marked this PR as Draft.

**Comment by feliperodri** [comment]
> > @AniruddhaKanhere while you work on this PR, could you convert it to draft? We're getting spurious alarms over CBMC proof failures.
> 
> I apologise. I have marked this PR as Draft.

No problem, thank you :)

**Pull request closed without merging**
