### PR TITLE
PR# 3: Update boot loader for RX65N-RSK

### PR DESCRIPTION
**Pull request by VanNamDinh**
Checklist:
----------
- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by leegeth** [comment]
@VanNamDinh , Merged PR2 #2236 after the approvals and it created a merge conflict in vendors/renesas/rx_mcu_boards/boards/rx65n-rsk/aws_demos/config_files/iot_pkcs11_config.h file, can you please resolve the conflict so that this change can be merged?

**Comment by VanNamDinh** [comment]
> @VanNamDinh , Merged PR2 #2236 after the approvals and it created a merge conflict in vendors/renesas/rx_mcu_boards/boards/rx65n-rsk/aws_demos/config_files/iot_pkcs11_config.h file, can you please resolve the conflict so that this change can be merged?

Hi @leegeth, I have just resolved the conflicts.

**Comment by leegeth** [comment]
> > @VanNamDinh , Merged PR2 #2236 after the approvals and it created a merge conflict in vendors/renesas/rx_mcu_boards/boards/rx65n-rsk/aws_demos/config_files/iot_pkcs11_config.h file, can you please resolve the conflict so that this change can be merged?
> 
> Hi @leegeth, I have just resolved the conflicts.

@VanNamDinh , Thanks. We will help with build checks, review and approvals for this PR

**Pull request merged**
