### PR TITLE
Updateing cypress assets

### PR DESCRIPTION
**Pull request by shuopeng-deng**
Updating vendors/cypress and projects/cypress to the lastest version
Description
-----------

Update vendors/cypress asset to use submodules and update them to the lastest version.
Update projects/cypress accordingly to match new cypress assets.
Checklist:
----------

- [ X] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by mingyue86010** [comment]
This PR somehow has confilct with the CI build check and cause the CI failed to get the submodule code. But we verified that the submodule code can be obtianed with the local setup. We are investing the problem now.

**Comment by mingyue86010** [comment]
@shuopeng-deng Have you test the MTB build with this PR? I pull the code from your branch and tired to build a demo project, however get this error message: 

"/Applications/ModusToolbox/tools_2.1/make/start.mk:393: *** Build support for the target device not found. Run "make getlibs" to ensure all required build and code dependencies are present..  Stop.
"

ps: The Cmake build works fine.

**Comment by shuopeng-deng** [comment]
Replaced with https://github.com/aws/amazon-freertos/pull/2815

**Pull request closed without merging**
