### PR TITLE
Test: fix ut build failure

### PR DESCRIPTION
**Pull request by alfred2g**
Fix ut build failure

Description
-----------
Fix UT build failure

Checklist:
----------

- [ X ] I have tested my changes. No regression in existing tests.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by aggarw13 — DISMISSED** [review]

**Review by n9wxu — APPROVED** [review]

**Review by n9wxu — CHANGES_REQUESTED** [review]
Pass the unit tests!

**Review by n9wxu — APPROVED** [review]

**Pull request merged**
