### PR TITLE
Add TFMv1.2 Release for CY8CKIT_064S0S2_4343W board

### PR DESCRIPTION
**Pull request by CharleyChu**
Description
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

IDT Result:

========== Test Summary ==========
Execution Time:         55m38s
Tests Completed:        107
Tests Passed:           101
Tests Failed:           6
Tests Skipped:          0
----------------------------------
Test Groups:
    FullMQTT:                   PASSED
    FreeRTOSVersion:            PASSED
    FreeRTOSIntegrity:          FAILED
    FullPKCS11_ECC:             PASSED
    FullSecureSockets:          PASSED
    FullPKCS11_Core:            PASSED
    FullPKCS11_RSA:             FAILED
    FullTLS:                    PASSED
Optional Test Groups:
    FullWiFi:           PASSED
----------------------------------

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by RaymondNgun** [comment]
@yngki - FYI

**Comment by lundinc2** [comment]
Hi @CharleyChu @RaymondNgun,

Nice talking to you earlier today. I am just waiting to receive my board so I can test this.

**Review by lundinc2 — APPROVED** [review]

**Review by dan4thewin — APPROVED** [review]

**Pull request merged**
