### PR TITLE
Common-IO UART Test Fixes

### PR DESCRIPTION
**Pull request by lundinc2**
Move UART async read to occur before call to async write in loopback test, for devices that don't buffer a write.
Add logic to UART cancel test for devices that do not support cancel.

Description
-----------

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by osloapps-max** [comment]
@lundinc2 

I've done the same changes as part of my work to refactor the test cases based on the following issue:
https://github.com/aws/amazon-freertos/issues/1859

I have attached my version of the UART tests, maybe this would be interesting for you for this pull request?
[test_iot_uart.zip](https://github.com/aws/amazon-freertos/files/4421995/test_iot_uart.zip)

**Comment by lundinc2** [comment]
@osloapps-max, 

Thanks! I took a look at those changes, they look great. Do you think you could open a pull request either to my fork's branch, or the master branch in the main repository so we can get those in? 

Preferably to the master branch, but which ever is easiest for you.

**Comment by osloapps-max** [comment]
@lundinc2 
I'm currently doing similar work for all of the ports I'm doing for the TI SimpleLink family, I expect to have gone over all possible ports in about two weeks (as next week is easter holiday where I live).

If you are OK with waiting for this, I could provide a pull request with similar updates for most of the tests in there today (a few excluded like USB etc as I only update test cases I can actually run). 

If not (and you want them faster), I could try to get an pull request up with what I got today early next week :)

**Comment by lundinc2** [comment]
@osloapps-max whatever is easiest for you. I do prefer smaller and frequent PRs, as they will be easier for me to review.

**Pull request merged**
