### PR TITLE
Fix the Psoc64 MTB project BLE demo build failure.

### PR DESCRIPTION
**Pull request by mingyue86010**
Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by AniruddhaKanhere** [comment]
Re-triggered the CBMC checks.

**Review by aggarg — APPROVED** [review]

**Pull request merged**
