### PR TITLE
style: Fix typo and alignment issue is iot_i2s.h

### PR DESCRIPTION
**Pull request by brianfr-amazon**
Fixing typo and style issue in comments of iot_i2s.h

Why:  nit fixes

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by hydedong** [comment]
did you upload your latest update? didn't see pvBuvver change

**Comment by brianfr-amazon** [comment]
I don't understand your question.

I was addressing the nit's you had in https://gerrit6.labcollab.net/gerrit/#/c/586535/?



________________________________

**Comment by hydedong** [comment]
change that gerrit and you will see you have one additional change that didn't show up in this PR

**Comment by hydedong** [comment]
talked offline, no issue, approved

**Pull request merged**
