### PR TITLE
No mangle POSIX headers

### PR DESCRIPTION
**Pull request by abelfodil**
No mangle POSIX headers

Description
-----------
No mangle POSIX headers when included in C++ code.

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

### CODE REVIEW

**Comment by abhidixi11** [comment]
Hello @abelfodil 
Thanks for the PR.
At this time we are not unable to accept external contributions.
Thanks.

**Comment by abhidixi11** [comment]
Hello @abelfodil,

Just curious,  is not having extern "C" causing any problems for you? 
If you use C++ compiler to compile C library code, you should not face any problems, but if you are running into any issue please let us know.
Thanks.

**Comment by abelfodil** [comment]
Hi @abhidixi11,

POSIX functions are implemented in C, so they are not mangled. If I include POSIX prototypes in my C++ code without explicitly telling the compiler they come from a C linkage, the compiler will mangle the signatures and the linkage will fail.

**Comment by abhidixi11** [comment]
Hello @abelfodil ,

Have you tried C++ compiler to compile everything (C++ code and C library) ?  extern "C" is typically needed if you want to use separate compilers. You can also use something like this in your C++ code if using one compiler does not work for you.
extern "C" {
#include "iot_mqtt.h"
}
Check this thread for similar discussion. 
https://github.com/aws/aws-iot-device-sdk-embedded-C/issues/314
Let me know if you have further questions.
Thanks.

**Comment by abelfodil** [comment]
Hi @abhidixi11,

I already wrap an `extern "C" {` around my include directives, but I made this PR to exactly not have to do that. 
See https://github.com/aws/amazon-freertos/blob/master/lib/include/FreeRTOS.h#L51 for example.

It is inconsistent to make the FreeRTOS interface interoperable with C++, but not applying the same treatment to the POSIX one.

**Comment by aggarg** [comment]
Hi @abelfodil,

Thanks for your reply. We are trying to understand what problem did you face when you compiled the code without ```extern "c" {```? In other words, if you remove ```extern "C"``` what error do you get?  

Thanks again.

**Comment by abelfodil** [comment]
When `extern "C"` isn't wrapped around C function prototypes in C++ code, I get the following error
`undefined reference to 'your_c_function(param_type param)'`

To understand why, see https://en.wikipedia.org/wiki/Name_mangling#Handling_of_C_symbols_when_linking_from_C++

**Comment by aggarg** [comment]
Thank you for the explanation. I think I understand what issue you are facing. To make it clear, let’s consider that you the following three files:

* interface.h – This file declares a function, say, ```void sample( void )``` and does not use ```extern "C"```.
* implementation.c – This file includes ```interface.h``` and implements the function ```sample```.
* usage.cpp – This file includes ```interface.h``` and usage the function ```sample```. 

There are two possible cases:
* If you are using C++ compiler for both implementation.c and usage.cpp: both compiled object files ```implemention.o``` and ```usage.o``` will have mangled symbol for ```sample``` and linker will succeed.
* If you are using C compiler for implementation.c and C++ compiler for usage.cpp: ```implementation.o``` will have non-mangled symbol while ```usage.o``` will have mangled symbol and the linker will fail. 

So I guess you are using two different compilers based on file extension. Would you please check that?

If that is the case, we will address it.

Thanks.

**Comment by abelfodil** [comment]
Exactly.

I am using two different compilers: `arm-none-eabi-gcc` for C and `arm-none-eabi-g++` for C++. It it not recommended to compile C code with a C++ compiler as the behavior might differ from the C standard.

**Comment by aggarg** [comment]
Hi @abelfodil,

Thank you very much for the explanation. We will fix this issue.

We are working on finalizing the process for accepting public contributions and unfortunately, as of now, we are unable to accept PRs.

Thanks again for your time.

**Comment by abelfodil** [comment]
Thank you very much for your patience. Should I remove my fork then?

**Comment by aggarg** [comment]
Yes, feel free to delete it. 

Thanks.

**Pull request closed without merging**
