### PR TITLE
update tracealyzer recorder library to 4.3.5

### PR DESCRIPTION
**Pull request by butlerpaul**
Signed-off-by: Paul Butler <butler.paul@gmail.com>

update tracealyzer recorder library to 4.3.5

Description
-----------
Version of tracealyzer recorder currently included in 3rdparty libs is out of date

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by butlerpaul** [comment]
The details for the failed checks are private. How do I find out what I need to do to move this PR forward?

**Comment by abhidixi11** [comment]
Hello Paul,

Thanks for the submission. I'll get back to you once I find out if we can accept these changes. We need to make sure the new version works with our code.
Thanks.

**Comment by yuhui-zheng** [comment]
Contacted offline. In the middle of sorting out Windows build error.

**Comment by dcgaws** [comment]
Paul, hello, per above, the GitHub hooks appear to be failing because the Amazon FreeRTOS project for the Windows Simulator is failing to build with these changes. Will you be able to resolve that and resubmit? Thank you.

**Comment by butlerpaul** [comment]
I’m traveling this week and next but will look at the build errors over the weekend. I’ll resubmit when I find the issue

**Comment by butlerpaul** [comment]
All builds are passing now. Anything else I need to provide?

**Comment by dan4thewin** [comment]
Hi, Paul.  Can you describe what testing has been done?

**Comment by butlerpaul** [comment]
I’ve only tested with tracelyzer on Ubuntu 16 and STM32.

**Comment by dan4thewin** [comment]
> I’ve only tested with tracelyzer on Ubuntu 16 and STM32.

On what boards and OS's do we support tracelyzer?

**Comment by butlerpaul** [comment]
Tracealyzer GUI runs on Windows and Linux. As far as I know, the trace data collection can be enabled in FreeRTOS (as well as many other RTOSs.) for any board. The data capture is sent to Tracealyzer for analysis.

**Pull request merged**
