### PR TITLE
Deprecate make build system on ESP32

### PR DESCRIPTION
**Pull request by shubhamkulkarni97**
Description
-----------
This PR deprecates make build system on ESP32 and added a error message in Makefile for aws_demos and aws_tests.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by yanjos-dev** [comment]
@shubhamkulkarni97 I checked the build failure and it looks like it's failing due to a bug that was occurring on the master branch. It was fixed in commit #2346 on the master branch. Can you rebase your changes on top of master?

**Comment by shubhamkulkarni97** [comment]
Hi @yanjos-dev, have rebased the changes on top of latest master.

**Comment by shubhamkulkarni97** [comment]
Hello @yanjos-dev,

If build issues are resolved, can we merge this PR?

Thanks,
Shubham

**Comment by yanjos-dev** [comment]
Hello @shubhamkulkarni97, we can merge the changes after the build issues are resolved and the PR has been approved.

**Pull request merged**
