### PR TITLE
Fixed macro error

### PR DESCRIPTION
**Pull request by DavidLin1577**
Description
-----------

Note that some macros are wrong, lucky is nobody uses them now, 
so fixed them to avoid more errors in the future:
SHARED_SECRET_MAX_LENGHT ->  SHARED_SECRET_MAX_LENGTH    
ECC_KEY_MAX_LENGHT ->  ECC_KEY_MAX_LENGTH    
AES_KEY_MAX_LENGHT_IN_BYTES -> AES_KEY_MAX_LENGTH_IN_BYTES

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by ravibhagavandas** [comment]
@DavidLin1577 

Could you also make sure the changes are merged into Nordic SDK upstream by posting the issue in this forum:

https://devzone.nordicsemi.com/f/nordic-q-a

**Comment by DavidLin1577** [comment]
> @DavidLin1577
> 
> Could you also make sure the changes are merged into Nordic SDK upstream by posting the issue in this forum:
> 
> https://devzone.nordicsemi.com/f/nordic-q-a

@ravibhagavandas That is a good idea. The upstream is also in github : [](https://github.com/NordicSemiconductor/Nordic-Thingy52-FW)
and I had made the same pr to the project Nordic-Thingy52-FW this morning, 
Thanks for your advise.

The upstream Nordic-Thingy52-FW PR:
[](https://github.com/NordicSemiconductor/Nordic-Thingy52-FW/pull/43)

**Comment by ravibhagavandas** [comment]
@DavidLin1577 

Thanks for raising the PR with Nordic. We will wait for https://github.com/NordicSemiconductor/Nordic-Thingy52-FW/pull/43 to be closed before merging this change.

**Pull request merged**
