### PR TITLE
Request to add OTA feature for RX65N-RSK

### PR DESCRIPTION
**Pull request by VanNamDinh**
Request to add OTA feature for RX65N-RSK

Description
-----------
Request to add OTA feature for RX65N-RSK

Checklist:
----------
- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by dan4thewin** [comment]
Hi, @VanNamDinh .  This PR is far too large to be meaningfully reviewed.  I think the best way to make progress would be to resubmit these changes as a series of smaller PRs, each of which is thematically cohesive (i.e., focusing on a single set of related ideas/changes).  Furthermore, it would be very valuable for you to request reviews from people you know with comprehensive knowledge of the RX65N-RSK as a first pass.

**Comment by gkwicker** [comment]
To add a little more detail to @dan4thewin's comment, I see a couple of areas of concern here:

1. This PR includes changes to FreeRTOS+TCP networking code (`libraries/freertos_plus/standard/freertos_plus_tcp/source/portable/NetworkInterface/RX/NetworkInterface.c`) which is shared among many different platforms.  If that change is required, it should be submitted in a separate pull request.  The same is true for any code outside of the `vendors/renesas` directory.
2. There are some .dll files in this directory (vendors/renesas/rx_mcu_boards/tools/mot_file_converter/packages/Newtonsoft.Json.12.0.2/lib/net20).  Those should not be distributed in this repository but rather [via the vendor's website.](https://www.newtonsoft.com/json)

**Comment by VanNamDinh** [comment]
Hi @gkwicker ,
Thanks for your support !
1. We will resubmit in a separate pull request as soon as possible.
2. We have a few questions regarding .dll files. So should we remove .dll files from this repository ?
We're going to move vendors/renesas/rx_mcu_boards/tools/mot_file_converter to our website or GitHub (convert tools repository maybe). For more details, we only keep all files in this direction vendors\renesas\rx_mcu_boards\tools\mot_file_converter\Renesas Secure Flash Programmer\bin\Debug. And then, upload it to our website or GitHub. Your team members can download it to run IDT tests. Is this ok?

**Comment by gkwicker** [comment]
> Hi @gkwicker ,
> Thanks for your support !
> 
>     1. We will resubmit in a separate pull request as soon as possible.
> 
>     2. We have a few questions regarding .dll files. So should we remove .dll files from this repository ?
>        We're going to move vendors/renesas/rx_mcu_boards/tools/mot_file_converter to our website or GitHub (convert tools repository maybe). For more details, we only keep all files in this direction vendors\renesas\rx_mcu_boards\tools\mot_file_converter\Renesas Secure Flash Programmer\bin\Debug. And then, upload it to our website or GitHub. Your team members can download it to run IDT tests. Is this ok?

In general it is best to distribute binary tools and .dll files on your website or the website of the tool vendor, and provide documentation here on how to download/install them so that the tests can be run.

**Pull request closed without merging**
