### PR TITLE
Delete test_iot_internal.h

### PR DESCRIPTION
**Pull request by haipengd**
Delete test_iot_internal.h
Description
It's not need for AFR

Checklist:
----------

- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by haipengd** [comment]
@qiutongs @vjjunnut, can you help to review this and approve?

**Comment by qiutongs** [comment]
We are actually using this header. https://github.com/aws/amazon-freertos/blob/master/libraries/abstractions/common_io/test/iot_test_common_io.c#L29

**Comment by qiutongs** [comment]
We can reopen this PR after discussion.

**Pull request closed without merging**
