### PR TITLE
Replace the ipconfigRAND32 macro with a function

### PR DESCRIPTION
**Pull request by htibosch**
Replace the ipconfigRAND32 macro with a function
-----------

Summary:

Any TCP/IP stack has a need for random numbers. Think of random port numbers and initial sequence numbers in a TCP connection. But also ID's when contacting a DNS server.

Until now, there was a macro `ipconfigRAND32()` that was usually defined as:

~~~c
extern uint32_t ulRand();
#define ipconfigRAND32()    ulRand()
~~~

When a random number is obtained from a peripheral, things may go wrong because of a hardware failure. We introduced the rule that a random value '0' stands for a failure.

However, the number 0 is a valid random number.

I propose a new function that delivers a random number, and that indicates if the operation was successful:

~~~c
/* xApplicationGetRandomNumber() will set *pulNumber to a random number,
and return pdTRUE. When the random number generator is broken, it shall return
pdFALSE.
The function is defined in 'iot_secure_sockets.c'.
If that module is not included in the project, the application must provide an
implementation of it.
The macro's ipconfigRAND32() and configRAND32() are not in use anymore. */
BaseType_t xApplicationGetRandomNumber( uint32_t *pulNumber );
~~~

Let the macro `ipconfigRAND32()` continue to exist for a while, also for backward compatibility.

Most importantly for now is that modules like FreeRTOS_DNS and FreeRTOS_TCP know if a random number of 0 means an error or a true random value.

The earlier ulRand() function can be implemented like this:

~~~c
#if 0
uint32_t ulRand( void )
{
	uint32_t ulNumber = 0uL;
	BaseType_t xResult = xApplicationGetRandomNumber( &( ulNumber ) );

	if( xResult == pdFALSE )
	{
		ulNumber = 0uL;
	}
	else
	{
		/* Function succeeded, a random number will be returned. */
	}
	return ulNumber;
}
#endif /* 0 */
~~~

 I put the function in an `#if 0` block to avoid compiling it. The compiler will point out where it has to be replaced with the new function `xApplicationGetRandomNumber()`.

Checklist:
----------

- [x] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

The code has not been linted yet because the entire FreeRTOS+TCP library has not been linted yet.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by lundinc2** [comment]
Hello @htibosch can you please uncrustify your changes.

**Comment by htibosch** [comment]
At this moment, within master, the following file havs not been uncrustified at all:

	vendors\infineon\boards\xmc4800_plus_optiga_trust_x\ports\secure_sockets\iot_secure_sockets.c

Currently uncrustified in my commit:

	vendors\vendor\boards\board\ports\secure_sockets\iot_secure_sockets.c
	libraries\abstractions\secure_sockets\freertos_plus_tcp\iot_secure_sockets.c
	vendors\infineon\boards\xmc4800_plus_optiga_trust_x\ports\secure_sockets\iot_secure_sockets.c

The 5 other files belong to FreeRTOS+TCP :

	FreeRTOS_IP.h
	FreeRTOS_DHCP.c
	FreeRTOS_DNS.c
	FreeRTOS_Sockets.c
	portable\NetworkInterface\WinPCap\FaultInjection.c

As the FreeRTOS+TCP is not yet curstified, I'd like to do this in a different PR.

**Comment by lundinc2** [comment]
> At this moment, within master, the following file has not been uncrustified at all:
> 
> ```
> vendors\infineon\boards\xmc4800_plus_optiga_trust_x\ports\secure_sockets\iot_secure_sockets.c
> ```
> 
> Currently uncrustified in my commit:
> 
> ```
> vendors\vendor\boards\board\ports\secure_sockets\iot_secure_sockets.c
> libraries\abstractions\secure_sockets\freertos_plus_tcp\iot_secure_sockets.c
> vendors\infineon\boards\xmc4800_plus_optiga_trust_x\ports\secure_sockets\iot_secure_sockets.c
> ```
> 
> The 5 other files belong to FreeRTOS+TCP :
> 
> ```
> FreeRTOS_IP.h
> FreeRTOS_DHCP.c
> FreeRTOS_DNS.c
> FreeRTOS_Sockets.c
> portable\NetworkInterface\WinPCap\FaultInjection.c
> ```
> 
> As the FreeRTOS+TCP is not yet curstified, I'd like to do this in a different PR.

Okay, that is reasonable. I requested it as the uncrustify hook failed. I will look into this and see if this can be avoided.

**Pull request merged**
