### PR TITLE
vendors/espressif: ESP-IDF `v4.4.2` upgrade and added support for ESP32-S3

### LINKED ISSUE #3459: Support for ESP32-S3?
Version release/v4.4 of Espressif esp-idf (https://github.com/espressif/esp-idf/tree/release/v4.4) already supports ESP32-S3.
image
Our new truck tracker system is intended to use it. I can upload very basic espressif's demos to it, but I can't do it for my project. Does AFR support for this new microcontroller in near future? Is there any timeline? Currently only v4.2 is supported on AFR.
image

### LINKED ISSUE #3494: [Feature Request] esp32s3 support
Is esp32s3 support planned?

### LINKED ISSUE #3518: [BUG] Core Dump fails compiling
**Describe the bug**

I get the following error when building my project trying to use coredump:
`
../amazon-freertos/vendors/espressif/esp-idf/components/espcoredump/src/core_dump_port.c: In function 'esp_core_dump_get_tasks_snapshot':
../amazon-freertos/vendors/espressif/esp-idf/components/espcoredump/src/core_dump_port.c:281:12: error: unknown type name 'TaskSnapshot_t'
     static TaskSnapshot_t s_tasks_snapshots[CONFIG_ESP32_CORE_DUMP_MAX_TASKS_NUM];
            ^~~~~~~~~~~~~~
../amazon-freertos/vendors/espressif/esp-idf/components/espcoredump/src/core_dump_port.c:285:27: error: 'TaskSnapshot_t' undeclared (first use in this function); did you mean 'TaskStatus_t'?
     _Static_assert(sizeof(TaskSnapshot_t) >= sizeof(core_dump_task_header_t), "FreeRTOS task snapshot binary compatibility issue!");
                           ^~~~~~~~~~~~~~
                           TaskStatus_t
../amazon-freertos/vendors/espressif/esp-idf/components/espcoredump/src/core_dump_port.c:285:27: note: each undeclared identifier is reported only once for each function it appears in
../amazon-freertos/vendors/espressif/esp-idf/components/espcoredump/src/core_dump_port.c:285:20: error: expression in static assertion is not an integer
     _Static_assert(sizeof(TaskSnapshot_t) >= sizeof(core_dump_task_header_t), "FreeRTOS task snapshot binary compatibility issue!");
                    ^~~~~~
../amazon-freertos/vendors/espressif/esp-idf/components/espcoredump/src/core_dump_port.c:287:35: error: implicit declaration of function 'uxTaskGetSnapshotAll'; did you mean 'uxTaskGetSystemState'? [-Werror=implicit-function-declaration]
     uint32_t task_num = (uint32_t)uxTaskGetSnapshotAll(s_tasks_snapshots,
                                   ^~~~~~~~~~~~~~~~~~~~
                                   uxTaskGetSystemState
cc1: some warnings being treated as errors
`

It looks like `uxTaskGetSnapshotAll` and `TaskSnapshot_t` are no longer defined in FreeRTOS. This issue echoes #2820. Is there any solution for this? I am using AFR latest version.

**System information**
- Hardware board: ESP32-WROOM-32D
- Operating System: Linux 
- Project/Demo: custom application

**Steps to reproduce bug**
Configure project to use coredump.
config_coredump
Build project using `idf.py build`.

### LINKED ISSUE #3534: [Feature Request] Update submodule "vendors/espressif/esp-idf" to release/v4.4 of esp-afr-sdk
**Describe the new feature request**
The esp-idf release/v4.4 or later supports external coex interface. This feature is required for the design with esp32s2 and external BLE chip that shares single antenna. 

**Describe other alternatives you've considered**
I couldn't find alternative. The coex function are part of esp_wifi componenent libnet80211.a

### PR DESCRIPTION
**Pull request by laukik-hase**
Description
-----------
- Updated the ESP-IDF submodule to the stable v4.4.2 release.
- Updated the Amazon FreeRTOS port for compatibility with ESP-IDF v4.4.2.
- Added support for `ESP32-S3` SoC

### Related
- Depends on https://github.com/FreeRTOS/FreeRTOS-Kernel/pull/572
- Resolves https://github.com/aws/amazon-freertos/issues/3459
- Resolves https://github.com/aws/amazon-freertos/issues/3494
- Closes https://github.com/aws/amazon-freertos/issues/3534
- Closes https://github.com/aws/amazon-freertos/issues/3518

### Notes
- The FreeRTOS-Kernel submodule for this PR is based on the latest main branch commit - https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/195a351ec797ba434c0e00fbba1d1f6adb74e279.
- The ESP-IDF v4.4.x release requires an updated toolchain (`xtensa-esp32xx-elf-gcc esp-2021r2-patch3-8.4.0`) and is not compatible with the older toolchain used in Amazon FreeRTOS (`xtensa-esp32xx-elf-gcc esp-2020r3-8.4.0`).
- For getting started with ESP32-S3, please refer to the guide [here](https://github.com/espressif/esp-afr-sdk/blob/release/v4.4/aws_freertos_esp32s3_getting_started_guide.md).
- Users who want to test this PR can use the following commands -
```
git fetch origin pull/3541/head:afr_branch
git checkout afr_branch
git submodule update --init --recursive --checkout
```

Checklist:
----------
- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by eelaix** [comment]
plz, merge this change to aws/amazon-freertos as soon as you can, I have download hase/amazon-freertos and build my esp32s2 code successful.

**Comment by laukik-hase** [comment]
Hello, @aggarg and @paulbartell!

This pull request updates ESP-IDF shipped with AFR to `v4.4.2` and also adds support for the ESP32-S3 SoC.

As mentioned, the `FreeRTOS-Kernel` submodule for this PR is based on the latest `main` branch commit - https://github.com/FreeRTOS/FreeRTOS-Kernel/commit/195a351ec797ba434c0e00fbba1d1f6adb74e279. The same for AFR `main` branch is set at `v10.4.3 LTS Patch 2` and there is a draft PR for updating it - https://github.com/aws/amazon-freertos/pull/3507.

Will we have to wait till the above draft PR is merged? Is there a plan to use only LTS versions of the FreeRTOS kernel in the AFR `main` branch henceforth?

CC: @mahavirj

**Comment by thomasklaush** [comment]
works without issues
I have download hase/amazon-freertos and build my esp32s3 code successful.

**Comment by n9wxu** [comment]
The iot-reference integration for the ESP32S2 can be found as part of this repo:
https://github.com/FreeRTOS/iot-reference-esp32c3
This repo uses IDF 4.4 so it has support for all ESP32 devices.

**Pull request closed without merging**
