### PR TITLE
MCUXpresso SDK FreeRTOS updates.

### PR DESCRIPTION
**Pull request by DavidJurajdaNXP**
List of NXP MCUX SDK modifications.
-----------

Task aware debugging support:
	- freertos_task_c_additions.h
	- add portARCH_NAME to CM33 portmacro.h
GCC -flto optimization support
	- vTaskSwitchContext attribute used in task.h
Enable definition of configCPU_CLOCK_HZ by variable instead of constant.
	- add external variable declaration to port.c (extern uint32_t SystemCoreClock;)
Add alternative memory alocator adapted for newlib.
	- heap_useNewlib.c
Replace configOVERRIDE_DEFAULT_TICK_CONFIGURATION in RVDS ports.
	- use generic solution __attribute__((weak))
Tickless for CM0
	- add external declaration of vPortSuppressTicksAndSleep into CM0 portmacro.h

Checklist:
----------

 Updates are rebased to master branch just for purpose of further discussion. 
- [ ] I have tested my changes. No regression in existing tests.
- [ ] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by RichardBarry** [comment]
Hi David - thanks for this contribution.  This is going to take some time to go through - below just starting with a high level:

- freertos_task_c_additions.h

Although this header file was originally added at NXP's request, it is now generally available for all users, and is often mentioned in the support forums when people want to add code into the tasks.c file without modifying the code.  That makes the file very much project specific rather than part of the kernel code - analogous to the FreeRTOSConfig.h file which would not be stored in a directory that is in the include path of all projects that use the kernel.  Your submission also includes what I think is NXP specific code - if some of that code is generally useful to all users then perhaps we can add it directly into the .c file to leave the header file available for all users.

- add portARCH_NAME to CM33 portmacro.h

I think this changes have already been done, but not synch'ed with Git yet.  Let me know if anything is missing: 
https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Source/portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/portmacro.h#l90 ... etc.

- GCC -flto optimization support
- vTaskSwitchContext attribute used in task.h

We have already done this too so it will be available here in the next sync (see portDONT_DISCARD):

https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Source/include/task.h#l2307

We do not allow any compiler or third party library specifics into the kernel code, hence we do not check for GCC inline using the pre-processor, but use a macro that is then defined in the compiler specific portmacro.h file.

which also means....

- Enable definition of configCPU_CLOCK_HZ by variable instead of constant.
- add external variable declaration to port.c (extern uint32_t SystemCoreClock;)

....I'm afraid we cannot include SystemCoreClock either, although I can't actually see where you use the variable that is externed.  If it relies on the variable being in the build then it will break the build for many thousands of developers, if it doesn't rely on SystemCoreClock being defined then the definition is redundant for those users.

What is the use case here?  Maybe we can find another way of achieving it?  I'm assuming you cannot just have the extern in FreeRTOSConfig.h, or #define configCPU_CLOCK_HZ to SystemCoreClock.

- Add alternative memory alocator adapted for newlib.
- heap_useNewlib.c

Will look in more detail.

- Replace configOVERRIDE_DEFAULT_TICK_CONFIGURATION in RVDS ports.
- use generic solution attribute((weak))

Weak attribute was not available at the time the code was written.  If there are no backward compatibility issues for users this would seem to be a simple change.

- Tickless for CM0
- add external declaration of vPortSuppressTicksAndSleep into CM0 portmacro.h

Enough people have done their own version of this that I agree it should be in the official distribution.

**Comment by RichardBarry** [comment]
Updates to some of my comments from my previous reply:

> 
> * add portARCH_NAME to CM33 portmacro.h
> 
> I think this changes have already been done, but not synch'ed with Git yet. Let me know if anything is missing:
> https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Source/portable/ARMv8M/non_secure/portable/GCC/ARM_CM33_NTZ/portmacro.h#l90 ... etc.
> 
> * GCC -flto optimization support
> * vTaskSwitchContext attribute used in task.h
> 
> We have already done this too so it will be available here in the next sync (see portDONT_DISCARD):
> 
> https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Source/include/task.h#l2307

These have now been merged into the Github repo.


> ....I'm afraid we cannot include SystemCoreClock either, although I can't actually see where you use the variable that is externed. If it relies on the variable being in the build then it will break the build for many thousands of developers, if it doesn't rely on SystemCoreClock being defined then the definition is redundant for those users.
> 
> What is the use case here? Maybe we can find another way of achieving it? I'm assuming you cannot just have the extern in FreeRTOSConfig.h, or #define configCPU_CLOCK_HZ to SystemCoreClock.

Would be interested in your reply to the above to see what we can do here.

> 
> * Add alternative memory alocator adapted for newlib.
> * heap_useNewlib.c
> 
> Will look in more detail.

This is similar to heap_3 already, which could be used with newlib, but doesn't provide sbrk() or configLINKER_HEAP_BASE_SYMBOL.  There are some application/environment/compiler specifics here so options would be either for you to provide this file yourself (as per the task c additions header file) or for this to be provided as a utlity c file in a similar way to the sprintf_stdarg c file.



Additionally - the setjmp/xJmpBuf suggestions - which I seem to have neglected to comment on previously.  These changes are isolated to a single compiler which allows us to make and test the changes without fear of breaking somebody else's builds, however I'm interested in the use case as most users will not have anything to return to.  Please let me know.

**Comment by abhidixi11** [comment]
Hello DavidJurajdaNXP,

Is this PR up to date ? Can you please resolve conflicts  ? Coding style checks are failing as well, we'll try to get back to you on that once conflicts are resolved.
Thanks.

**Comment by DavidJurajdaNXP** [comment]
Hi all,

@abhidixi11
Pull Request is not ready for merge. It is only resource for broader discussion.
It is not planned to merge it directly.

@RichardBarry 

I have removed following requirements from pull request:
    - freertos_tasks_c_additions.h
    - heap_useNewlib.c
    - extern uint32_t SystemCoreClock in port.c
    - Scheduler ending support

Explanation:
Will be covered on NXP side in CMSIS pack vendor extension for FreeRTOS 
    - freertos_tasks_c_additions.h
    - heap_useNewlib.c

Could be covered in FreeRTOSConfig.h
    - extern uint32_t SystemCoreClock in port.c

Scheduler ending functionality is required for gcov coverage tests enablement, but it could be stripped from official support.
    - Scheduler ending support

Remaining requirements to discuss are:
    - vPortSuppressTicksAndSleep support for CM0
    - configOVERRIDE_DEFAULT_TICK_CONFIGURATION -> __attribute__((weak)) in RVDS

Regards,
David

**Comment by DavidJurajdaNXP** [comment]
Hi all,

@RichardBarry 
Remaining requirements to discuss are:
    **- vPortSuppressTicksAndSleep support for CM0
    - configOVERRIDE_DEFAULT_TICK_CONFIGURATION -> __attribute__((weak)) in RVDS**

I have removed following requirements from pull request:
    - freertos_tasks_c_additions.h
    - heap_useNewlib.c
    - extern uint32_t SystemCoreClock in port.c
    - Scheduler ending support

Explanation:
Will be covered on NXP side in CMSIS pack vendor extension for FreeRTOS 
    - freertos_tasks_c_additions.h
    - heap_useNewlib.c

Could be covered in FreeRTOSConfig.h
    - extern uint32_t SystemCoreClock in port.c

Scheduler ending functionality is required for gcov coverage tests enablement, but it could be stripped from official support.
    - Scheduler ending support

@abhidixi11
Pull Request is not ready for merge. It is only resource for broader discussion.
It is not planned to merge it directly.

Regards,
David

**Comment by yuhui-zheng** [comment]
@DavidJurajdaNXP 

I got the hardware and I'm in the middle of testing my two PRs linked above. Since it has been a while (apologize..), could you confirm we should be able to fully resolve this thread once: 1, tickless is supported in CM0 port(s); 2, weak linkage is updated in CM3 and CM4 ports?

**Comment by DavidJurajdaNXP** [comment]
Hi @yuhui-zheng,

CM0 and CM4 tickless support is most important for us. We would like to add tickless support also for CM33, but let's start with CM0 and CM4. Should I prepare isolated pull request? Do you need any reference or package?

Tickless support list should also include RVDS week unification:
3. Replace configOVERRIDE_DEFAULT_TICK_CONFIGURATION in RVDS ports.
    - use generic solution attribute((weak))

We would like to cover also inconsistency in API prvSetupTimerInterrupt/vPortSetupTimerInterrupt.

Feel free to contact me anytime here or via email.

Regards,
David

**Comment by yuhui-zheng** [comment]
Thanks @DavidJurajdaNXP. I think I'll be fine without additional PR or reference for now. 

**In regards to tickless --**
* I'll merge tickless for GCC/Keil/IAR CM0 into kernel repository, and it'll be included in future releases. 

* For CM4 are you looking for tickless in MPU or non-MPU port? I believe CM4 non-MPU port already supports tickless. Linking below:  
GCC/CM_4F (non-MPU) --
https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c#l511 
Keil/CM_4F (non-MPU) -- 
https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Source/portable/RVDS/ARM_CM4F/port.c#l524
IAR/CM_4F (non-MPU) --
https://sourceforge.net/p/freertos/code/HEAD/tree/trunk/FreeRTOS/Source/portable/IAR/ARM_CM4F/port.c#l387

* CM33 is also on track by another colleague, I believe. 

**In regards to weak linkage --**
* I'll merge the update along with tickless into kernel directory.

Seems we've got you covered for this thread. Will keep this PR open for one more week.


Regards,
Yuki

**Comment by yuhui-zheng** [comment]
@DavidJurajdaNXP  I'm closing this thread now. Things are currently under review (see below reference links if interested), and will be merged to upstream shortly. 

* M0 tickles: 
https://github.com/yuhui-zheng/FreeRTOS/tree/LPC51U68_M0+_Xpresso 
(Could try out demo projects under ```./FreeRTOS/Demo/CORTEX_M0+_LPC51U68_LPCXpresso/```, GCC/Keil/IAR projects could be found there.)
* M3/M4 weak linkage: 
https://github.com/yuhui-zheng/FreeRTOS/tree/CORTEX_M3_4_Keil_weak_linkage

**Pull request closed without merging**
