### PR TITLE
PR #5: aws_demos and aws_tests for OTA

### PR DESCRIPTION
**Pull request by VanNamDinh**
- [x] I have tested my changes. No regression in existing tests.
- [x] My code is Linted.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by leegeth** [comment]
@VanNamDinh, Merged PR2 #2236 after the approvals and it created a merge conflict in as reported, can you please resolve the conflicts so that this change can be merged?

**Comment by lundinc2** [comment]
Hello @VanNamDinh,

I have merged PRs 3 and 4, and this has caused a merge conflict in the PAL. Do you mind resolving this?

Thanks

**Comment by VanNamDinh** [comment]
> Hello @VanNamDinh,
> 
> I have merged PRs 3 and 4, and this has caused a merge conflict in the PAL. Do you mind resolving this?
> 
> Thanks

Hello @lundinc2 , I have resolved conflict.

**Comment by lundinc2** [comment]
Thank you for the quick response @VanNamDinh it is much appreciated!

**Pull request merged**
